### ISSUE TITLE
Improve error messages when matching devices

### ISSUE THREAD

**Issue by dbankieris** [nasa/IDF#43]
Devices must match vendor and product IDs and may optionally require an interface number, serial number, and path. We need specific error message for each case.

**Comment by hefrimu** [comment]
Will this work also with a SpaceNavigator for Notebooks PN: 3DX-700034 ?

**Comment by dbankieris** [comment]
IDF supports the SpaceNavigator, yes. The models I've seen have had USB product numbers 0xC626 and 0xC628. If yours has a different product number, you can pass it to UsbSpaceNavigator's [constructor](https://github.com/nasa/IDF/blob/master/include/idf/UsbSpaceNavigator.hh#L31). You can find the product number via `lsusb`: 

Bus 003 Device 008: ID **054c:0268** Sony Corp. Batoh Device / PlayStation 3 Controller

The **bold** text is vendor_id:product_id
