### ISSUE TITLE
IDF library should be compiled with -fPIC 

### ISSUE THREAD

**Issue by alexlin0** [nasa/IDF#6]
I want  to include the IDF library in a shared library.  To do so I needed to add -fPIC to the CPPFLAGS in the top level Makefile.  BTW: CPPFLAGS should be CXXFLAGS.  CXXFLAGS are for the compiler, CPPFLAGS are for the preprocessor.

**Comment by dbankieris** [comment]
An informative thread essentially arguing that non-PIC is obsolete:  
https://groups.google.com/forum/#!msg/gnu.gcc.help/3zKY-ylbnnA/_HnuYTaylAoJ
