### ISSUE TITLE
Microsoft XBox One

### ISSUE THREAD

**Issue by stephenmontgomerysmith** [nasa/IDF#82]
I wrote a patch so that the Microsoft XBox One controller works with IDF.  (It has a slightly different protocol than the Microsoft XBox 360.)
[IDF-patch.txt](https://github.com/nasa/IDF/files/10170436/IDF-patch.txt)

FYI, I am also available at stephen.j.montgomery-smith@nasa.gov

**Comment by stephenmontgomerysmith** [comment]
I just found out how to make it into a pull request.  So go look there.

**Comment by prkunz** [comment]
Great, Thank you! I'll take a look

**Comment by prkunz** [comment]
> I just found out how to make it into a pull request. So go look there.

Yeah, looks like you checked all the boxes. I don't have access to an xbox one controller to test it on. Thank you!

**Comment by genti337** [comment]
@prkunz I pushed updates to the add an instance for the Xbox One controller to SingleFlightController, SingleCameraController, and SingleRoboticController classes on the branch `82_xbox_one_ctl`.  Please let me know if you see any issues.

**Comment by prkunz** [comment]
It looks good, but for one thing. The parameter type for calling `createInstance` should use the controller's parent class `XboxOne` so that eventually if there is the need to use a XboxOne controller remotely, a `RemoteXboxOne` can be created and will work without needing another `createInstance` overload

**Comment by genti337** [comment]
Good catch, I just pushed a fix for that in commit 9cefa8d.

**Comment by prkunz** [comment]
Looks good. Go ahead and create a Pull Request
